import { Button } from "@/components/ui/button";
import Link from "next/link";
import { SignedIn, SignedOut, SignInButton, SignUpButton } from "@clerk/nextjs";
import { PLANS } from "@/utils/plans";

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)]"> {/* Adjust height considering header */} 

      {/* Hero Section */}
      <section className="flex-1 flex items-center justify-center text-center bg-gradient-to-b from-background to-muted/50 py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
              Effortless YouTube Summaries with AI
            </h1>
            <p className="text-lg text-muted-foreground md:text-xl">
              Stop wasting time watching long videos. Get the key insights and main points in seconds with our powerful AI summarizer.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <SignedOut>
                <SignUpButton mode="modal">
                  <Button size="lg">Get Started Free</Button>
                </SignUpButton>
                <SignInButton mode="modal">
                  <Button size="lg" variant="secondary">Sign In</Button>
                </SignInButton>
              </SignedOut>
              <SignedIn>
                <Button size="lg" asChild><Link href="/dashboard">Go to Dashboard</Link></Button>
              </SignedIn>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Why Choose Us?</h2>
            <p className="text-muted-foreground md:text-lg mt-2">Key features that make summarizing simple.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="p-6 border rounded-lg bg-card text-center">
              {/* Icon Placeholder */}
              <div className="mx-auto mb-4 h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center text-primary">💡</div>
              <h3 className="text-xl font-semibold mb-2">Instant Summaries</h3>
              <p className="text-muted-foreground">Paste a YouTube link and get a concise summary generated by AI almost instantly.</p>
            </div>
            {/* Feature 2 */}
            <div className="p-6 border rounded-lg bg-card text-center">
              {/* Icon Placeholder */}
              <div className="mx-auto mb-4 h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center text-primary">🎯</div>
              <h3 className="text-xl font-semibold mb-2">Accurate & Relevant</h3>
              <p className="text-muted-foreground">Our AI focuses on extracting the most important information and key takeaways.</p>
            </div>
            {/* Feature 3 */}
            <div className="p-6 border rounded-lg bg-card text-center">
              {/* Icon Placeholder */}
              <div className="mx-auto mb-4 h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center text-primary">🖱️</div>
              <h3 className="text-xl font-semibold mb-2">Simple Interface</h3>
              <p className="text-muted-foreground">Clean, intuitive design makes summarizing videos straightforward and hassle-free.</p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="py-12 md:py-24 lg:py-32 bg-muted/50">
        <div className="container px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Get Started in 3 Easy Steps</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
            <div className="p-6">
              <div className="mb-4 inline-block rounded-lg bg-primary px-3 py-1 text-sm font-medium text-primary-foreground">Step 1</div>
              <h3 className="text-xl font-semibold mb-2">Paste URL</h3>
              <p className="text-muted-foreground">Copy the full URL of the YouTube video you want to summarize.</p>
            </div>
            <div className="p-6">
              <div className="mb-4 inline-block rounded-lg bg-primary px-3 py-1 text-sm font-medium text-primary-foreground">Step 2</div>
              <h3 className="text-xl font-semibold mb-2">Click Summarize</h3>
              <p className="text-muted-foreground">Paste the link into our app and hit the summarize button.</p>
            </div>
            <div className="p-6">
              <div className="mb-4 inline-block rounded-lg bg-primary px-3 py-1 text-sm font-medium text-primary-foreground">Step 3</div>
              <h3 className="text-xl font-semibold mb-2">Read Summary</h3>
              <p className="text-muted-foreground">Get your AI-generated summary in moments. Save time, learn faster.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Use Cases Section */}
      <section id="use-cases" className="py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6">
           <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Perfect For...</h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
             {/* Use Case 1 */}
            <div>
              <p className="text-4xl mb-2">🎓</p>
              <p className="font-medium">Students</p>
            </div>
             {/* Use Case 2 */}
            <div>
              <p className="text-4xl mb-2">💼</p>
              <p className="font-medium">Professionals</p>
            </div>
             {/* Use Case 3 */}
            <div>
              <p className="text-4xl mb-2">🔬</p>
              <p className="font-medium">Researchers</p>
            </div>
             {/* Use Case 4 */}
            <div>
              <p className="text-4xl mb-2">✍️</p>
              <p className="font-medium">Creators</p>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-12 md:py-24 lg:py-32 bg-muted/50">
        <div className="container px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Simple Pricing</h2>
            <p className="text-muted-foreground md:text-lg mt-2">Choose the plan that works for you.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {PLANS.map((plan) => (
              <div 
                key={plan.id}
                className={`p-8 border rounded-lg bg-card flex flex-col relative ${
                  plan.id === 'pro' ? 'border-2 border-primary' : ''
                }`}
              >
                {plan.id === 'pro' && (
                  <div className="absolute top-0 right-0 mr-4 -mt-3 bg-primary text-primary-foreground text-xs font-semibold px-2 py-1 rounded">
                    POPULAR
                  </div>
                )}
                <h3 className="text-2xl font-semibold mb-4">{plan.name}</h3>
                <p className="text-4xl font-bold mb-2">
                  ${plan.price}
                  <span className="text-lg font-normal text-muted-foreground">/month</span>
                </p>
                <ul className="space-y-2 text-muted-foreground mt-4 mb-8 flex-grow">
                  {plan.features.map((feature, index) => (
                    <li key={index} className="flex items-center">
                      <span className="mr-2">✓</span>
                      {feature}
                    </li>
                  ))}
                </ul>
                <SignedOut>
                  {plan.id === 'free' ? (
                    <SignUpButton mode="modal">
                      <Button className="w-full mt-auto" variant="outline">Get Started</Button>
                    </SignUpButton>
                  ) : (
                    <SignUpButton mode="modal">
                      <Button className="w-full mt-auto">Subscribe to {plan.name}</Button>
                    </SignUpButton>
                  )}
                </SignedOut>
                <SignedIn>
                  <Button 
                    className="w-full mt-auto" 
                    variant={plan.id === 'free' ? 'outline' : 'default'}
                    asChild
                  >
                    <Link href="/dashboard/billing">
                      {plan.id === 'free' ? 'Current Plan' : 'Upgrade to ' + plan.name}
                    </Link>
                  </Button>
                </SignedIn>
              </div>
            ))}
          </div>
        </div>
      </section>

       {/* CTA Section */}
      <section className="py-12 md:py-24 lg:py-32 text-center bg-background">
        <div className="container px-4 md:px-6">
          <div className="max-w-2xl mx-auto space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Ready to Save Time?</h2>
            <p className="text-muted-foreground md:text-lg">
              Sign up today and start summarizing YouTube videos in seconds. Get started for free!
            </p>
             <SignedOut>
                <SignUpButton mode="modal">
                  <Button size="lg">Sign Up Now</Button>
                </SignUpButton>
             </SignedOut>
             <SignedIn>
                <Button size="lg" asChild><Link href="/dashboard">Go to Dashboard</Link></Button>
            </SignedIn>
          </div>
        </div>
      </section>

      {/* Footer Section */}
      <footer className="py-6 border-t bg-muted/50">
        <div className="container px-4 md:px-6 flex flex-col md:flex-row items-center justify-between text-sm text-muted-foreground">
          <p>&copy; 2024 YouTube Summarizer AI. All rights reserved.</p>
          <div className="flex gap-4 mt-4 md:mt-0">
            <Link href="#" className="hover:text-primary">Terms of Service</Link>
            <Link href="#" className="hover:text-primary">Privacy Policy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}